name: eQTLGenPhase2Env
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - anaconda
dependencies:
  - python=2.7.15
  - setuptools=41.0.1
  - vcftools=0.1.14
  - bcftools=1.9
  - tabix=0.2.6
  - gcc_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - r-base=3.6.1
  - r-data.table=1.12.2
  - r-stringr=1.4.0
  - java-jdk=8.0.112
  - gawk=5.0.1
  - coreutils=8.31
  - bitarray=1.0.1
  - Cython=0.29.13
  - h5py=2.10.0
  - conda-forge::numpy=1.16.2=py27_blas_openblash1522bff_0
  - conda-forge::pandas=0.24.2
  - conda-forge::scipy=1.2.1=py27_blas_openblash1522bff_0
  - pytables
  - natsort
  - conda-forge::pycryptodomex=3.9.7=py27h516909a_0
prefix: ./eQTLGenPhase2Env
